name: Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.17.1
      - name: Setup pages, install required dependencies
        run: yarn install
      - name: Build with quasar
        run: yarn build:pwa
      - name: Run tests
        run: echo 'Unimplemented command now.'
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production
          path: ./dist/pwa
  deploy:
    name: github-pages
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download production-ready build files
        uses: actions/download-artifact@v2
        with:
          name: production
          path: ./dist/pwa
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/pwa
          publish_branch: github-pages
          full_commit_message: 'feat: Automatic generated.'
